include_guard(GLOBAL)
set(PE_PROJECT_NATIVE_DIR "" CACHE PATH "C++ script source folder (optional project_native.cmake); empty builds the sample")
set(PE_PROJECT_NATIVE_ROOT "${CMAKE_CURRENT_LIST_DIR}")

function(pe_project_native_configure_runtime)
    # The runtime header is also included by ScriptSystem consumers.
    target_include_directories(PhasmaRuntime PUBLIC "${PE_PROJECT_NATIVE_ROOT}/Api")
    if(PE_PROJECT_NATIVE)
        target_compile_definitions(PhasmaRuntime PRIVATE PE_PROJECT_NATIVE=1)
    endif()
endfunction()

# Descriptors carry only the source filename, never the build machine's path (see ScriptModule.h).
function(pe_project_native_name_sources)
    foreach(source IN LISTS ARGN)
        get_filename_component(name "${source}" NAME)
        set_property(SOURCE "${source}" APPEND PROPERTY COMPILE_DEFINITIONS "PHASMA_SOURCE_NAME=\"${name}\"")
    endforeach()
endfunction()

function(pe_project_native_add_library)
    if(NOT PE_PROJECT_NATIVE)
        return()
    endif()
    set(native_dir "${PE_PROJECT_NATIVE_ROOT}/Sample")
    if(PE_PROJECT_NATIVE_DIR)
        set(native_dir "${PE_PROJECT_NATIVE_DIR}")
    endif()
    file(GLOB_RECURSE discovered_sources CONFIGURE_DEPENDS "${native_dir}/*.cpp")
    set(PE_PROJECT_NATIVE_SOURCES ${discovered_sources})
    set(PE_PROJECT_NATIVE_INCLUDE_DIRS)
    if(EXISTS "${native_dir}/project_native.cmake")
        include("${native_dir}/project_native.cmake")
        if(NOT PE_PROJECT_NATIVE_SOURCES)
            message(FATAL_ERROR "project_native.cmake must set PE_PROJECT_NATIVE_SOURCES")
        endif()
    endif()
    list(APPEND PE_PROJECT_NATIVE_SOURCES ${discovered_sources} "${PE_PROJECT_NATIVE_ROOT}/Module.cpp")
    list(REMOVE_DUPLICATES PE_PROJECT_NATIVE_SOURCES)
    pe_project_native_name_sources(${PE_PROJECT_NATIVE_SOURCES})
    if(CMAKE_SYSTEM_NAME STREQUAL "Android")
        add_library(PhasmaProjectNative STATIC ${PE_PROJECT_NATIVE_SOURCES})
        set_target_properties(PhasmaProjectNative PROPERTIES POSITION_INDEPENDENT_CODE ON)
        target_compile_definitions(PhasmaRuntime PRIVATE PE_PROJECT_NATIVE_STATIC=1)
        if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.24)
            target_link_libraries(PhasmaRuntime PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,PhasmaProjectNative>")
        else()
            target_link_libraries(PhasmaRuntime PRIVATE -Wl,--whole-archive PhasmaProjectNative -Wl,--no-whole-archive)
        endif()
    else()
        add_library(PhasmaProjectNative SHARED ${PE_PROJECT_NATIVE_SOURCES})
    endif()
    set_target_properties(PhasmaProjectNative PROPERTIES
        OUTPUT_NAME PhasmaGame
        CXX_STANDARD 20 CXX_STANDARD_REQUIRED ON
        CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON)
    target_include_directories(PhasmaProjectNative PRIVATE
        "${PE_PROJECT_NATIVE_ROOT}/Api" ${PE_PROJECT_NATIVE_INCLUDE_DIRS})
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Android")
        file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/$<CONFIG>/NativeScripts.json" CONTENT
            "{\"cmake\":\"${CMAKE_COMMAND}\",\"build\":\"${CMAKE_BINARY_DIR}\",\"config\":\"$<CONFIG>\",\"sources\":\"${native_dir}\"}\n")
    endif()
    # No engine linkage or PCH: the only dependency is the public scripting header.
endfunction()

function(pe_link_project_native target)
    if(TARGET PhasmaProjectNative)
        add_dependencies(${target} PhasmaProjectNative)
    endif()
endfunction()
