#version 450

struct Skin
{
	mat4 inverseBindMatrices[];
	uint joints[]; // Node index in buffer
};

struct Node
{
	mat4 matrix;
	uint parent; // Node index in buffer
	Skin skin;
};

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer DataIn
{
	vec4 info;
	Node nodes[];
} dataIn;

layout(std430, binding = 1) writeonly buffer DataOut
{
	mat4 matrices[];
} dataOut;


void main()
{

}