glslangValidator.exe -V Common/quad.vert -o Common/vert.spv
glslangValidator.exe -V GUI/shaderGUI.vert -o GUI/vert.spv
glslangValidator.exe -V GUI/shaderGUI.frag -o GUI/frag.spv
glslangValidator.exe -V Shadows/shaderShadows.vert -o Shadows/vert.spv
glslangValidator.exe -V SkyBox/shaderSkyBox.vert -o SkyBox/vert.spv
glslangValidator.exe -V SkyBox/shaderSkyBox.frag -o SkyBox/frag.spv
glslangValidator.exe -V Deferred/gBuffer.vert -o Deferred/vert.spv
glslangValidator.exe -V Deferred/gBuffer.frag -o Deferred/frag.spv
glslangValidator.exe -V Deferred/composition.vert -o Deferred/cvert.spv
glslangValidator.exe -V Deferred/composition.frag -o Deferred/cfrag.spv
glslangValidator.exe -V SSR/ssr.frag -o SSR/frag.spv
glslangValidator.exe -V Compute/shader.comp -o Compute/comp.spv
glslangValidator.exe -V SSAO/ssao.frag -o SSAO/frag.spv
glslangValidator.exe -V SSAO/ssaoBlur.frag -o SSAO/fragBlur.spv
glslangValidator.exe -V FXAA/FXAA.frag -o FXAA/frag.spv
glslangValidator.exe -V TAA/TAA.frag -o TAA/frag.spv
glslangValidator.exe -V TAA/TAASharpen.frag -o TAA/fragSharpen.spv
glslangValidator.exe -V Bloom/brightFilter.frag -o Bloom/fragBrightFilter.spv
glslangValidator.exe -V Bloom/gaussianBlurHorizontal.frag -o Bloom/fragGaussianBlurHorizontal.spv
glslangValidator.exe -V Bloom/gaussianBlurVertical.frag -o Bloom/fragGaussianBlurVertical.spv
glslangValidator.exe -V Bloom/combine.frag -o Bloom/fragCombine.spv
glslangValidator.exe -V MotionBlur/motionBlur.frag -o MotionBlur/frag.spv
glslangValidator.exe -V DepthOfField/DOF.frag -o DepthOfField/frag.spv