#include <webgpu/webgpu.h>
#include "Utils.h"

namespace
{

    struct ProcEntry
    {
        const char *name;
        WGPUProc proc;
    };

    // Sorted alphabetically — keep sorted when adding entries (binary search).
    static const ProcEntry s_procs[] = {
        {"wgpuAdapterAddRef", reinterpret_cast<WGPUProc>(wgpuAdapterAddRef)},
        {"wgpuAdapterGetFeatures", reinterpret_cast<WGPUProc>(wgpuAdapterGetFeatures)},
        {"wgpuAdapterGetInfo", reinterpret_cast<WGPUProc>(wgpuAdapterGetInfo)},
        {"wgpuAdapterGetLimits", reinterpret_cast<WGPUProc>(wgpuAdapterGetLimits)},
        {"wgpuAdapterHasFeature", reinterpret_cast<WGPUProc>(wgpuAdapterHasFeature)},
        {"wgpuAdapterInfoFreeMembers", reinterpret_cast<WGPUProc>(wgpuAdapterInfoFreeMembers)},
        {"wgpuAdapterRelease", reinterpret_cast<WGPUProc>(wgpuAdapterRelease)},
        {"wgpuAdapterRequestDevice", reinterpret_cast<WGPUProc>(wgpuAdapterRequestDevice)},
        {"wgpuBindGroupAddRef", reinterpret_cast<WGPUProc>(wgpuBindGroupAddRef)},
        {"wgpuBindGroupLayoutAddRef", reinterpret_cast<WGPUProc>(wgpuBindGroupLayoutAddRef)},
        {"wgpuBindGroupLayoutRelease", reinterpret_cast<WGPUProc>(wgpuBindGroupLayoutRelease)},
        {"wgpuBindGroupLayoutSetLabel", reinterpret_cast<WGPUProc>(wgpuBindGroupLayoutSetLabel)},
        {"wgpuBindGroupRelease", reinterpret_cast<WGPUProc>(wgpuBindGroupRelease)},
        {"wgpuBindGroupSetLabel", reinterpret_cast<WGPUProc>(wgpuBindGroupSetLabel)},
        {"wgpuBufferAddRef", reinterpret_cast<WGPUProc>(wgpuBufferAddRef)},
        {"wgpuBufferDestroy", reinterpret_cast<WGPUProc>(wgpuBufferDestroy)},
        {"wgpuBufferGetConstMappedRange", reinterpret_cast<WGPUProc>(wgpuBufferGetConstMappedRange)},
        {"wgpuBufferGetMapState", reinterpret_cast<WGPUProc>(wgpuBufferGetMapState)},
        {"wgpuBufferGetMappedRange", reinterpret_cast<WGPUProc>(wgpuBufferGetMappedRange)},
        {"wgpuBufferGetSize", reinterpret_cast<WGPUProc>(wgpuBufferGetSize)},
        {"wgpuBufferGetUsage", reinterpret_cast<WGPUProc>(wgpuBufferGetUsage)},
        {"wgpuBufferMapAsync", reinterpret_cast<WGPUProc>(wgpuBufferMapAsync)},
        {"wgpuBufferReadMappedRange", reinterpret_cast<WGPUProc>(wgpuBufferReadMappedRange)},
        {"wgpuBufferRelease", reinterpret_cast<WGPUProc>(wgpuBufferRelease)},
        {"wgpuBufferSetLabel", reinterpret_cast<WGPUProc>(wgpuBufferSetLabel)},
        {"wgpuBufferUnmap", reinterpret_cast<WGPUProc>(wgpuBufferUnmap)},
        {"wgpuBufferWriteMappedRange", reinterpret_cast<WGPUProc>(wgpuBufferWriteMappedRange)},
        {"wgpuCommandBufferAddRef", reinterpret_cast<WGPUProc>(wgpuCommandBufferAddRef)},
        {"wgpuCommandBufferRelease", reinterpret_cast<WGPUProc>(wgpuCommandBufferRelease)},
        {"wgpuCommandBufferSetLabel", reinterpret_cast<WGPUProc>(wgpuCommandBufferSetLabel)},
        {"wgpuCommandEncoderAddRef", reinterpret_cast<WGPUProc>(wgpuCommandEncoderAddRef)},
        {"wgpuCommandEncoderBeginComputePass", reinterpret_cast<WGPUProc>(wgpuCommandEncoderBeginComputePass)},
        {"wgpuCommandEncoderBeginRenderPass", reinterpret_cast<WGPUProc>(wgpuCommandEncoderBeginRenderPass)},
        {"wgpuCommandEncoderClearBuffer", reinterpret_cast<WGPUProc>(wgpuCommandEncoderClearBuffer)},
        {"wgpuCommandEncoderCopyBufferToBuffer", reinterpret_cast<WGPUProc>(wgpuCommandEncoderCopyBufferToBuffer)},
        {"wgpuCommandEncoderCopyBufferToTexture", reinterpret_cast<WGPUProc>(wgpuCommandEncoderCopyBufferToTexture)},
        {"wgpuCommandEncoderCopyTextureToBuffer", reinterpret_cast<WGPUProc>(wgpuCommandEncoderCopyTextureToBuffer)},
        {"wgpuCommandEncoderCopyTextureToTexture", reinterpret_cast<WGPUProc>(wgpuCommandEncoderCopyTextureToTexture)},
        {"wgpuCommandEncoderFinish", reinterpret_cast<WGPUProc>(wgpuCommandEncoderFinish)},
        {"wgpuCommandEncoderInsertDebugMarker", reinterpret_cast<WGPUProc>(wgpuCommandEncoderInsertDebugMarker)},
        {"wgpuCommandEncoderPopDebugGroup", reinterpret_cast<WGPUProc>(wgpuCommandEncoderPopDebugGroup)},
        {"wgpuCommandEncoderPushDebugGroup", reinterpret_cast<WGPUProc>(wgpuCommandEncoderPushDebugGroup)},
        {"wgpuCommandEncoderRelease", reinterpret_cast<WGPUProc>(wgpuCommandEncoderRelease)},
        {"wgpuCommandEncoderResolveQuerySet", reinterpret_cast<WGPUProc>(wgpuCommandEncoderResolveQuerySet)},
        {"wgpuCommandEncoderSetLabel", reinterpret_cast<WGPUProc>(wgpuCommandEncoderSetLabel)},
        {"wgpuCommandEncoderWriteTimestamp", reinterpret_cast<WGPUProc>(wgpuCommandEncoderWriteTimestamp)},
        {"wgpuComputePassEncoderAddRef", reinterpret_cast<WGPUProc>(wgpuComputePassEncoderAddRef)},
        {"wgpuComputePassEncoderDispatchWorkgroups", reinterpret_cast<WGPUProc>(wgpuComputePassEncoderDispatchWorkgroups)},
        {"wgpuComputePassEncoderDispatchWorkgroupsIndirect", reinterpret_cast<WGPUProc>(wgpuComputePassEncoderDispatchWorkgroupsIndirect)},
        {"wgpuComputePassEncoderEnd", reinterpret_cast<WGPUProc>(wgpuComputePassEncoderEnd)},
        {"wgpuComputePassEncoderInsertDebugMarker", reinterpret_cast<WGPUProc>(wgpuComputePassEncoderInsertDebugMarker)},
        {"wgpuComputePassEncoderPopDebugGroup", reinterpret_cast<WGPUProc>(wgpuComputePassEncoderPopDebugGroup)},
        {"wgpuComputePassEncoderPushDebugGroup", reinterpret_cast<WGPUProc>(wgpuComputePassEncoderPushDebugGroup)},
        {"wgpuComputePassEncoderRelease", reinterpret_cast<WGPUProc>(wgpuComputePassEncoderRelease)},
        {"wgpuComputePassEncoderSetBindGroup", reinterpret_cast<WGPUProc>(wgpuComputePassEncoderSetBindGroup)},
        {"wgpuComputePassEncoderSetLabel", reinterpret_cast<WGPUProc>(wgpuComputePassEncoderSetLabel)},
        {"wgpuComputePassEncoderSetPipeline", reinterpret_cast<WGPUProc>(wgpuComputePassEncoderSetPipeline)},
        {"wgpuComputePipelineAddRef", reinterpret_cast<WGPUProc>(wgpuComputePipelineAddRef)},
        {"wgpuComputePipelineGetBindGroupLayout", reinterpret_cast<WGPUProc>(wgpuComputePipelineGetBindGroupLayout)},
        {"wgpuComputePipelineRelease", reinterpret_cast<WGPUProc>(wgpuComputePipelineRelease)},
        {"wgpuComputePipelineSetLabel", reinterpret_cast<WGPUProc>(wgpuComputePipelineSetLabel)},
        {"wgpuCreateInstance", reinterpret_cast<WGPUProc>(wgpuCreateInstance)},
        {"wgpuDeviceAddRef", reinterpret_cast<WGPUProc>(wgpuDeviceAddRef)},
        {"wgpuDeviceCreateBindGroup", reinterpret_cast<WGPUProc>(wgpuDeviceCreateBindGroup)},
        {"wgpuDeviceCreateBindGroupLayout", reinterpret_cast<WGPUProc>(wgpuDeviceCreateBindGroupLayout)},
        {"wgpuDeviceCreateBuffer", reinterpret_cast<WGPUProc>(wgpuDeviceCreateBuffer)},
        {"wgpuDeviceCreateCommandEncoder", reinterpret_cast<WGPUProc>(wgpuDeviceCreateCommandEncoder)},
        {"wgpuDeviceCreateComputePipeline", reinterpret_cast<WGPUProc>(wgpuDeviceCreateComputePipeline)},
        {"wgpuDeviceCreateComputePipelineAsync", reinterpret_cast<WGPUProc>(wgpuDeviceCreateComputePipelineAsync)},
        {"wgpuDeviceCreatePipelineLayout", reinterpret_cast<WGPUProc>(wgpuDeviceCreatePipelineLayout)},
        {"wgpuDeviceCreateQuerySet", reinterpret_cast<WGPUProc>(wgpuDeviceCreateQuerySet)},
        {"wgpuDeviceCreateRenderBundleEncoder", reinterpret_cast<WGPUProc>(wgpuDeviceCreateRenderBundleEncoder)},
        {"wgpuDeviceCreateRenderPipeline", reinterpret_cast<WGPUProc>(wgpuDeviceCreateRenderPipeline)},
        {"wgpuDeviceCreateRenderPipelineAsync", reinterpret_cast<WGPUProc>(wgpuDeviceCreateRenderPipelineAsync)},
        {"wgpuDeviceCreateSampler", reinterpret_cast<WGPUProc>(wgpuDeviceCreateSampler)},
        {"wgpuDeviceCreateShaderModule", reinterpret_cast<WGPUProc>(wgpuDeviceCreateShaderModule)},
        {"wgpuDeviceCreateTexture", reinterpret_cast<WGPUProc>(wgpuDeviceCreateTexture)},
        {"wgpuDeviceDestroy", reinterpret_cast<WGPUProc>(wgpuDeviceDestroy)},
        {"wgpuDeviceGetAdapterInfo", reinterpret_cast<WGPUProc>(wgpuDeviceGetAdapterInfo)},
        {"wgpuDeviceGetFeatures", reinterpret_cast<WGPUProc>(wgpuDeviceGetFeatures)},
        {"wgpuDeviceGetLimits", reinterpret_cast<WGPUProc>(wgpuDeviceGetLimits)},
        {"wgpuDeviceGetLostFuture", reinterpret_cast<WGPUProc>(wgpuDeviceGetLostFuture)},
        {"wgpuDeviceGetQueue", reinterpret_cast<WGPUProc>(wgpuDeviceGetQueue)},
        {"wgpuDeviceHasFeature", reinterpret_cast<WGPUProc>(wgpuDeviceHasFeature)},
        {"wgpuDevicePopErrorScope", reinterpret_cast<WGPUProc>(wgpuDevicePopErrorScope)},
        {"wgpuDevicePushErrorScope", reinterpret_cast<WGPUProc>(wgpuDevicePushErrorScope)},
        {"wgpuDeviceRelease", reinterpret_cast<WGPUProc>(wgpuDeviceRelease)},
        {"wgpuDeviceSetLabel", reinterpret_cast<WGPUProc>(wgpuDeviceSetLabel)},
        {"wgpuExternalTextureAddRef", reinterpret_cast<WGPUProc>(wgpuExternalTextureAddRef)},
        {"wgpuExternalTextureRelease", reinterpret_cast<WGPUProc>(wgpuExternalTextureRelease)},
        {"wgpuExternalTextureSetLabel", reinterpret_cast<WGPUProc>(wgpuExternalTextureSetLabel)},
        {"wgpuGetInstanceFeatures", reinterpret_cast<WGPUProc>(wgpuGetInstanceFeatures)},
        {"wgpuGetInstanceLimits", reinterpret_cast<WGPUProc>(wgpuGetInstanceLimits)},
        {"wgpuGetProcAddress", reinterpret_cast<WGPUProc>(wgpuGetProcAddress)},
        {"wgpuHasInstanceFeature", reinterpret_cast<WGPUProc>(wgpuHasInstanceFeature)},
        {"wgpuInstanceAddRef", reinterpret_cast<WGPUProc>(wgpuInstanceAddRef)},
        {"wgpuInstanceCreateSurface", reinterpret_cast<WGPUProc>(wgpuInstanceCreateSurface)},
        {"wgpuInstanceGetWGSLLanguageFeatures", reinterpret_cast<WGPUProc>(wgpuInstanceGetWGSLLanguageFeatures)},
        {"wgpuInstanceHasWGSLLanguageFeature", reinterpret_cast<WGPUProc>(wgpuInstanceHasWGSLLanguageFeature)},
        {"wgpuInstanceProcessEvents", reinterpret_cast<WGPUProc>(wgpuInstanceProcessEvents)},
        {"wgpuInstanceRelease", reinterpret_cast<WGPUProc>(wgpuInstanceRelease)},
        {"wgpuInstanceRequestAdapter", reinterpret_cast<WGPUProc>(wgpuInstanceRequestAdapter)},
        {"wgpuInstanceWaitAny", reinterpret_cast<WGPUProc>(wgpuInstanceWaitAny)},
        {"wgpuPipelineLayoutAddRef", reinterpret_cast<WGPUProc>(wgpuPipelineLayoutAddRef)},
        {"wgpuPipelineLayoutRelease", reinterpret_cast<WGPUProc>(wgpuPipelineLayoutRelease)},
        {"wgpuPipelineLayoutSetLabel", reinterpret_cast<WGPUProc>(wgpuPipelineLayoutSetLabel)},
        {"wgpuQuerySetAddRef", reinterpret_cast<WGPUProc>(wgpuQuerySetAddRef)},
        {"wgpuQuerySetDestroy", reinterpret_cast<WGPUProc>(wgpuQuerySetDestroy)},
        {"wgpuQuerySetGetCount", reinterpret_cast<WGPUProc>(wgpuQuerySetGetCount)},
        {"wgpuQuerySetGetType", reinterpret_cast<WGPUProc>(wgpuQuerySetGetType)},
        {"wgpuQuerySetRelease", reinterpret_cast<WGPUProc>(wgpuQuerySetRelease)},
        {"wgpuQuerySetSetLabel", reinterpret_cast<WGPUProc>(wgpuQuerySetSetLabel)},
        {"wgpuQueueAddRef", reinterpret_cast<WGPUProc>(wgpuQueueAddRef)},
        {"wgpuQueueOnSubmittedWorkDone", reinterpret_cast<WGPUProc>(wgpuQueueOnSubmittedWorkDone)},
        {"wgpuQueueRelease", reinterpret_cast<WGPUProc>(wgpuQueueRelease)},
        {"wgpuQueueSetLabel", reinterpret_cast<WGPUProc>(wgpuQueueSetLabel)},
        {"wgpuQueueSubmit", reinterpret_cast<WGPUProc>(wgpuQueueSubmit)},
        {"wgpuQueueWriteBuffer", reinterpret_cast<WGPUProc>(wgpuQueueWriteBuffer)},
        {"wgpuQueueWriteTexture", reinterpret_cast<WGPUProc>(wgpuQueueWriteTexture)},
        {"wgpuRenderBundleAddRef", reinterpret_cast<WGPUProc>(wgpuRenderBundleAddRef)},
        {"wgpuRenderBundleEncoderAddRef", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderAddRef)},
        {"wgpuRenderBundleEncoderDraw", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderDraw)},
        {"wgpuRenderBundleEncoderDrawIndexed", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderDrawIndexed)},
        {"wgpuRenderBundleEncoderDrawIndexedIndirect", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderDrawIndexedIndirect)},
        {"wgpuRenderBundleEncoderDrawIndirect", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderDrawIndirect)},
        {"wgpuRenderBundleEncoderFinish", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderFinish)},
        {"wgpuRenderBundleEncoderInsertDebugMarker", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderInsertDebugMarker)},
        {"wgpuRenderBundleEncoderPopDebugGroup", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderPopDebugGroup)},
        {"wgpuRenderBundleEncoderPushDebugGroup", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderPushDebugGroup)},
        {"wgpuRenderBundleEncoderRelease", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderRelease)},
        {"wgpuRenderBundleEncoderSetBindGroup", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderSetBindGroup)},
        {"wgpuRenderBundleEncoderSetIndexBuffer", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderSetIndexBuffer)},
        {"wgpuRenderBundleEncoderSetLabel", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderSetLabel)},
        {"wgpuRenderBundleEncoderSetPipeline", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderSetPipeline)},
        {"wgpuRenderBundleEncoderSetVertexBuffer", reinterpret_cast<WGPUProc>(wgpuRenderBundleEncoderSetVertexBuffer)},
        {"wgpuRenderBundleRelease", reinterpret_cast<WGPUProc>(wgpuRenderBundleRelease)},
        {"wgpuRenderBundleSetLabel", reinterpret_cast<WGPUProc>(wgpuRenderBundleSetLabel)},
        {"wgpuRenderPassEncoderAddRef", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderAddRef)},
        {"wgpuRenderPassEncoderBeginOcclusionQuery", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderBeginOcclusionQuery)},
        {"wgpuRenderPassEncoderDraw", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderDraw)},
        {"wgpuRenderPassEncoderDrawIndexed", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderDrawIndexed)},
        {"wgpuRenderPassEncoderDrawIndexedIndirect", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderDrawIndexedIndirect)},
        {"wgpuRenderPassEncoderDrawIndirect", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderDrawIndirect)},
        {"wgpuRenderPassEncoderEnd", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderEnd)},
        {"wgpuRenderPassEncoderEndOcclusionQuery", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderEndOcclusionQuery)},
        {"wgpuRenderPassEncoderExecuteBundles", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderExecuteBundles)},
        {"wgpuRenderPassEncoderInsertDebugMarker", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderInsertDebugMarker)},
        {"wgpuRenderPassEncoderPopDebugGroup", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderPopDebugGroup)},
        {"wgpuRenderPassEncoderPushDebugGroup", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderPushDebugGroup)},
        {"wgpuRenderPassEncoderRelease", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderRelease)},
        {"wgpuRenderPassEncoderSetBindGroup", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderSetBindGroup)},
        {"wgpuRenderPassEncoderSetBlendConstant", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderSetBlendConstant)},
        {"wgpuRenderPassEncoderSetIndexBuffer", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderSetIndexBuffer)},
        {"wgpuRenderPassEncoderSetLabel", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderSetLabel)},
        {"wgpuRenderPassEncoderSetPipeline", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderSetPipeline)},
        {"wgpuRenderPassEncoderSetScissorRect", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderSetScissorRect)},
        {"wgpuRenderPassEncoderSetStencilReference", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderSetStencilReference)},
        {"wgpuRenderPassEncoderSetVertexBuffer", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderSetVertexBuffer)},
        {"wgpuRenderPassEncoderSetViewport", reinterpret_cast<WGPUProc>(wgpuRenderPassEncoderSetViewport)},
        {"wgpuRenderPipelineAddRef", reinterpret_cast<WGPUProc>(wgpuRenderPipelineAddRef)},
        {"wgpuRenderPipelineGetBindGroupLayout", reinterpret_cast<WGPUProc>(wgpuRenderPipelineGetBindGroupLayout)},
        {"wgpuRenderPipelineRelease", reinterpret_cast<WGPUProc>(wgpuRenderPipelineRelease)},
        {"wgpuRenderPipelineSetLabel", reinterpret_cast<WGPUProc>(wgpuRenderPipelineSetLabel)},
        {"wgpuSamplerAddRef", reinterpret_cast<WGPUProc>(wgpuSamplerAddRef)},
        {"wgpuSamplerRelease", reinterpret_cast<WGPUProc>(wgpuSamplerRelease)},
        {"wgpuSamplerSetLabel", reinterpret_cast<WGPUProc>(wgpuSamplerSetLabel)},
        {"wgpuShaderModuleAddRef", reinterpret_cast<WGPUProc>(wgpuShaderModuleAddRef)},
        {"wgpuShaderModuleGetCompilationInfo", reinterpret_cast<WGPUProc>(wgpuShaderModuleGetCompilationInfo)},
        {"wgpuShaderModuleRelease", reinterpret_cast<WGPUProc>(wgpuShaderModuleRelease)},
        {"wgpuShaderModuleSetLabel", reinterpret_cast<WGPUProc>(wgpuShaderModuleSetLabel)},
        {"wgpuSupportedFeaturesFreeMembers", reinterpret_cast<WGPUProc>(wgpuSupportedFeaturesFreeMembers)},
        {"wgpuSupportedInstanceFeaturesFreeMembers", reinterpret_cast<WGPUProc>(wgpuSupportedInstanceFeaturesFreeMembers)},
        {"wgpuSupportedWGSLLanguageFeaturesFreeMembers", reinterpret_cast<WGPUProc>(wgpuSupportedWGSLLanguageFeaturesFreeMembers)},
        {"wgpuSurfaceAddRef", reinterpret_cast<WGPUProc>(wgpuSurfaceAddRef)},
        {"wgpuSurfaceCapabilitiesFreeMembers", reinterpret_cast<WGPUProc>(wgpuSurfaceCapabilitiesFreeMembers)},
        {"wgpuSurfaceConfigure", reinterpret_cast<WGPUProc>(wgpuSurfaceConfigure)},
        {"wgpuSurfaceGetCapabilities", reinterpret_cast<WGPUProc>(wgpuSurfaceGetCapabilities)},
        {"wgpuSurfaceGetCurrentTexture", reinterpret_cast<WGPUProc>(wgpuSurfaceGetCurrentTexture)},
        {"wgpuSurfacePresent", reinterpret_cast<WGPUProc>(wgpuSurfacePresent)},
        {"wgpuSurfaceRelease", reinterpret_cast<WGPUProc>(wgpuSurfaceRelease)},
        {"wgpuSurfaceSetLabel", reinterpret_cast<WGPUProc>(wgpuSurfaceSetLabel)},
        {"wgpuSurfaceUnconfigure", reinterpret_cast<WGPUProc>(wgpuSurfaceUnconfigure)},
        {"wgpuTextureAddRef", reinterpret_cast<WGPUProc>(wgpuTextureAddRef)},
        {"wgpuTextureCreateView", reinterpret_cast<WGPUProc>(wgpuTextureCreateView)},
        {"wgpuTextureDestroy", reinterpret_cast<WGPUProc>(wgpuTextureDestroy)},
        {"wgpuTextureGetDepthOrArrayLayers", reinterpret_cast<WGPUProc>(wgpuTextureGetDepthOrArrayLayers)},
        {"wgpuTextureGetDimension", reinterpret_cast<WGPUProc>(wgpuTextureGetDimension)},
        {"wgpuTextureGetFormat", reinterpret_cast<WGPUProc>(wgpuTextureGetFormat)},
        {"wgpuTextureGetHeight", reinterpret_cast<WGPUProc>(wgpuTextureGetHeight)},
        {"wgpuTextureGetMipLevelCount", reinterpret_cast<WGPUProc>(wgpuTextureGetMipLevelCount)},
        {"wgpuTextureGetSampleCount", reinterpret_cast<WGPUProc>(wgpuTextureGetSampleCount)},
        {"wgpuTextureGetTextureBindingViewDimension", reinterpret_cast<WGPUProc>(wgpuTextureGetTextureBindingViewDimension)},
        {"wgpuTextureGetUsage", reinterpret_cast<WGPUProc>(wgpuTextureGetUsage)},
        {"wgpuTextureGetWidth", reinterpret_cast<WGPUProc>(wgpuTextureGetWidth)},
        {"wgpuTextureRelease", reinterpret_cast<WGPUProc>(wgpuTextureRelease)},
        {"wgpuTextureSetLabel", reinterpret_cast<WGPUProc>(wgpuTextureSetLabel)},
        {"wgpuTextureViewAddRef", reinterpret_cast<WGPUProc>(wgpuTextureViewAddRef)},
        {"wgpuTextureViewRelease", reinterpret_cast<WGPUProc>(wgpuTextureViewRelease)},
        {"wgpuTextureViewSetLabel", reinterpret_cast<WGPUProc>(wgpuTextureViewSetLabel)},
    };

    static constexpr size_t s_procCount = sizeof(s_procs) / sizeof(s_procs[0]);

} // anonymous namespace

extern "C"
{

    WGPUProc wgpuGetProcAddress(WGPUStringView procName)
    {
        if (!procName.data)
            return nullptr;

        std::string name = pwgpu::ToString(procName);

        size_t lo = 0, hi = s_procCount;
        while (lo < hi)
        {
            size_t mid = lo + (hi - lo) / 2;
            int cmp = name.compare(s_procs[mid].name);
            if (cmp == 0)
                return s_procs[mid].proc;
            if (cmp < 0)
                hi = mid;
            else
                lo = mid + 1;
        }
        return nullptr;
    }

} // extern "C"
