-- Main entry point: runs all test suites

function init()
    run_acceleration_structure_tests()
    run_buffer_tests()
    run_command_tests()
    run_debug_tests()
    run_descriptor_tests()
    run_event_tests()
    run_framebuffer_tests()
    run_helpers_tests()
    run_image_tests()
    run_pipeline_tests()
    run_queue_tests()
    run_rhi_tests()
    run_semaphore_tests()
    run_shader_tests()
    run_surface_tests()
    run_swapchain_tests()
    run_vertex_tests()

    -- Editor-level bindings
    run_camera_tests()
    run_engine_tests()
    run_light_tests()
    run_material_tests()
    run_model_tests()
    run_particle_tests()
    run_scene_tests()
    run_settings_tests()
    run_skybox_tests()
    run_shader_file_tests()
    run_filesystem_tests()
end
