#pragma once

#include <algorithm>
#include <any>
#include <array>
#include <atomic>
#include <bitset>
#include <cassert>
#include <cctype>
#include <chrono>
#include <codecvt>
#include <condition_variable>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <deque>
#include <execution>
#include <filesystem>
#include <fstream>
#include <functional>
#include <future>
#include <initializer_list>
#include <iostream>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <shared_mutex>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <thread>
#include <tuple>
#include <type_traits>
#include <typeindex>
#include <typeinfo>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>

#include "SDL2/SDL.h"
#include "SDL2/SDL_syswm.h"
#include "SDL2/SDL_vulkan.h"
#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
#include "vulkan/vulkan.hpp"
#include "vma/vk_mem_alloc.h"
#if defined(PE_WIN32)
#include <d3d12.h>
#include <d3dcompiler.h>
#include <dxgi1_6.h>
#include <share.h>
#include <psapi.h>
#include <windows.h>
#elif defined(PE_LINUX)
#include <dlfcn.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/sysinfo.h>
#include <unistd.h>
#endif

#include "Base/Log.h"
#include "Base/Defines.h"
#include "Base/Enums.h"
#include "Base/Settings.h"
#include "Base/Hash.h"
#include "Base/Math.h"
#include "Base/Base.h"
#include "Base/Path.h"
#include "Base/ThreadPool.h"
#include "Base/Delegate.h"
#include "Base/Timer.h"
#include "Base/FileSystem.h"
#include "Base/FileWatcher.h"
#include "Base/EventSystem.h"

#include "ECS/Component.h"
#include "ECS/System.h"
#include "ECS/Entity.h"
#include "ECS/Context.h"

#include "API/Debug.h"
#include "API/Helpers.h"

#define STBI_MSC_SECURE_CRT