#!/usr/bin/env python3
"""Regenerate the embedded SPD bytecode: python tools/generate_downsampler_shaders.py --dxc <dxc>."""
import argparse
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
DIRECTORY = ROOT / "Phasma/Core/Code/API/Downsampler"


def generate(dxc, output):
    source = DIRECTORY / "Shaders/SPDIntegration.hlsl"
    current = (DIRECTORY / "DownsamplerShaders.inl").read_text()
    reflection = current[current.index('static constexpr const char *kDownsamplerReflectionSource'):]
    version = subprocess.check_output([str(dxc), "--version"], text=True).strip().replace("\n", "; ")
    chunks = ["// Generated by tools/generate_downsampler_shaders.py; do not edit bytecode by hand.\n",
              f"// DXC: {version}\n"]
    with tempfile.TemporaryDirectory(prefix="phasma-spd-") as directory:
        target = Path(directory) / "shader.bin"
        for name, image_format in [("kDownsamplerSpirv", "rgba32f"),
                                   ("kDownsamplerDxil", None),
                                   ("kDownsamplerSpirvRgba8", "rgba8"),
                                   ("kDownsamplerSpirvRgba16f", "rgba16f"),
                                   ("kDownsamplerSpirvRg16f", "rg16f")]:
            args = [str(dxc), str(source), "-E", "main", "-T", "cs_6_3" if image_format else "cs_6_6",
                    "-Fo", str(target)]
            if image_format:
                args += ["-spirv", "-fspv-target-env=vulkan1.2", "-D", f'SPD_IMAGE_FORMAT="{image_format}"']
            else:
                args += ["-Qstrip_debug", "-O3"]
            subprocess.run(args, check=True)
            data = target.read_bytes()
            chunks.append(f"\nstatic constexpr unsigned char {name}[] = {{\n")
            chunks.extend("  " + ", ".join(f"0x{byte:02x}" for byte in data[i:i+12]) + (",\n" if i + 12 < len(data) else "\n")
                          for i in range(0, len(data), 12))
            chunks.append(f"}};\nstatic constexpr unsigned int {name}_len = {len(data)};\n")
    chunks.append("\n" + reflection)
    output.write_text("".join(chunks), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dxc", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=DIRECTORY / "DownsamplerShaders.inl")
    args = parser.parse_args()
    generate(args.dxc, args.output)
