#!/usr/bin/env python3
"""new_game.py — scaffold a self-contained PhasmaEngine mini-game project.

Emits, under <dir>/<Name>/:
  phasma_project.json          4-field descriptor (startup_scene = main.pescene)
  Assets/Scenes/main.pescene   topdown_arena template (scene_scripts.on_play wired)
  Assets/Scripts/<name>.lua     entry script (player + input + waves + HUD)
  Assets/Scripts/gamekit/*       pinned snapshot of the engine gamekit + json.lua
  Assets/Prefabs/*.peprefab      pinned snapshot of the prefab pack
  run_smoke.ps1                  writes phasma_settings.json + launches PhasmaPlayer

Projects are self-contained (gamekit/prefabs are COPIED, like the tracked binaries
in PhasmaProjects) so they keep working independent of the engine tree. Re-run with
--update-gamekit to refresh the copied gamekit/prefab snapshot in place.

Usage:
  python tools/new_game.py --name MyGame [--template topdown]
                           [--dir C:\\Users\\Christos\\repos\\PhasmaProjects]
                           [--api vulkan] [--update-gamekit]
"""

import argparse
import json
import os
import re
import shutil

import minigamekit as mgk

DEFAULT_DIR = r"C:\Users\Christos\repos\PhasmaProjects"
DEFAULT_PLAYER_EXE = os.path.join(mgk.ENGINE_ROOT, "build-ninja-full", "Release", "PhasmaPlayer.exe")


# --- entry script template -------------------------------------------------

ENTRY_TEMPLATE = r'''-- {Name} — generated by tools/new_game.py (MiniGameKit topdown template).
--
-- This is the scene's on_play entry script: it runs with PlayerOnly lifecycle when
-- the scene enters play (immediately, in the standalone player). It bootstraps the
-- gamekit and wires a minimal topdown loop: WASD player movement, an enemy wave
-- drawn from the authored pool, a follow camera, and the HUD. Edit freely.

-- Bootstrap gamekit (PhasmaEngine's Lua does not wire `require`; load it via fs).
local kit = (function()
    local path = "Scripts/gamekit/init.lua"
    local src = fs.read(path)
    if not src then error("[{name}] gamekit not found at " .. path) end
    return load(src, "@" .. path, "t", _ENV)()
end)()

-- Smoke the scene.instantiate_prefab binding: drop one pickup near the start.
local pickup = scene.instantiate_prefab("Prefabs/pickup.peprefab")
if pickup and pickup.set_position then
    pickup:set_position(vec3(3.0, 0.4, 3.0))
    kit.log("spawned pickup prefab")
else
    kit.log("WARNING: pickup prefab did not instantiate")
end

-- Player ---------------------------------------------------------------------
local player_node = kit.scene.find("Player")
local player = kit.actor.wrap(player_node, {{ speed = 7.0, hp = 100 }})

kit.input.bind("move", {{ up = "W", down = "S", left = "A", right = "D" }})

-- Follow camera (orthographic, angled). Refines the authored Camera_0 each frame.
local cam = kit.camera.topdown(player_node, {{ height = 30.0, angle = 62.0, lerp = 8.0, size = 22.0 }})
kit.loop.add(function(dt) cam:update(dt) end, "post")

-- Enemy pool + waves ---------------------------------------------------------
local enemies = kit.pool.new("Enemy", 64)
local spawn_points = {{
    {{ x = -14.0, y = 0.5, z = -14.0 }}, {{ x = 14.0, y = 0.5, z = -14.0 }},
    {{ x = -14.0, y = 0.5, z = 14.0 }},  {{ x = 14.0, y = 0.5, z = 14.0 }},
    {{ x = 0.0,   y = 0.5, z = -16.0 }}, {{ x = 0.0,  y = 0.5, z = 16.0 }},
}}

local hud_wave = kit.scene.find("HUD_Wave")
local hud_hp = kit.scene.find("HUD_HP")
local wave_num = 0

local function start_wave()
    wave_num = wave_num + 1
    local w = kit.wave.new({{ pool = enemies, points = spawn_points, count = 8, interval = 0.6 }})
    w:on_clear(function() kit.timer.after(1.5, start_wave) end)
    kit.loop.add(function(dt) w:update(dt) end, "main")
    w:start()
    if hud_wave then kit.ui.text(hud_wave, "WAVE " .. wave_num) end
    kit.log("wave start wave=" .. wave_num)
end

-- Enemies home in on the player; on contact they "hit" and recycle to the pool,
-- so a wave eventually clears and the next begins.
kit.loop.add(function(dt)
    local pp = player:position()
    enemies:each_active(function(node)
        local p = node:get_position()
        local dx, dz = pp.x - p.x, pp.z - p.z
        local dist = math.sqrt(dx * dx + dz * dz)
        if dist <= 1.2 then
            player:damage(6)
            enemies:release(node)
        else
            local step = 3.5 * dt
            node:set_position(vec3(p.x + dx / dist * step, p.y, p.z + dz / dist * step))
        end
    end)
end, "main")

-- Player control + HUD -------------------------------------------------------
kit.loop.add(function(dt)
    player:move_dir(kit.input.axis2("move"), dt)
    if hud_hp then kit.ui.bar(hud_hp, player:hp_fraction(), {{ label = "HP", width = 14, tint = true }}) end
    if player.dead then -- survive-forever smoke: respawn so the loop keeps running
        player.hp, player.dead = player.max_hp, false
    end
end, "main")

start_wave()
kit.start()
kit.log("{name} ready")
'''


# --- run_smoke.ps1 template -------------------------------------------------

SMOKE_TEMPLATE = r'''# run_smoke.ps1 — launch {Name} in PhasmaPlayer and assert it loads cleanly.
# Generated by tools/new_game.py. Writes phasma_settings.json next to the player
# exe (that is where ResolveProjectSelection looks), force-exits any stale player,
# launches with the configured graphics API, waits, then checks the engine log.
$ErrorActionPreference = "Stop"

$exe       = "{exe}"
$project   = "{project}"
$api       = "{api}"
$startup   = "Assets/Scenes/main.pescene"

if (-not (Test-Path $exe)) {{ Write-Host "SMOKE FAIL: player exe not found: $exe"; exit 3 }}
$exeDir = Split-Path $exe
$settings = Join-Path $exeDir "phasma_settings.json"
$log = Join-Path $exeDir "PhasmaEngine.log"

# Point the player at this project.
@{{ project_path = $project; startup_scene = $startup }} | ConvertTo-Json | Set-Content -Encoding UTF8 $settings

# Force-exit any stale player and clear the old log so our run is unambiguous.
Get-Process PhasmaPlayer -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep -Milliseconds 500
if (Test-Path $log) {{ Remove-Item -Force $log -ErrorAction SilentlyContinue }}

Write-Host "Launching $exe --api $api ..."
$proc = Start-Process $exe -ArgumentList '--api', $api, '--display', '0' -WorkingDirectory $exeDir -PassThru
Start-Sleep -Seconds 18

$alive = -not $proc.HasExited
if (-not $alive) {{ Write-Host ("SMOKE: player EXITED early code=0x{{0:X8}}" -f $proc.ExitCode) }}
else {{ Write-Host "SMOKE: player ALIVE after 18s (pid=$($proc.Id))" }}

$logText = ""
if (Test-Path $log) {{ $logText = Get-Content $log -Raw }}

$sceneLoaded = $logText -match "Scene loaded from:"
$prefabOk    = $logText -match "Prefab instantiated from:"
$waveOk      = $logText -match "wave start wave="
$luaErr      = ($logText -split "`n" | Where-Object {{ $_ -match "\[Lua\].*error" }})

Write-Host "scene loaded:        $sceneLoaded"
Write-Host "prefab instantiated: $prefabOk"
Write-Host "wave started:        $waveOk"
if ($luaErr) {{ Write-Host "LUA ERRORS:"; $luaErr | ForEach-Object {{ Write-Host "  $_" }} }}

Write-Host "----- tail of PhasmaEngine.log -----"
if ($logText) {{ ($logText -split "`n" | Select-Object -Last 25) | ForEach-Object {{ Write-Host $_ }} }}

# Leave the player running so a human can drive WASD; pass -Stop to kill it.
if ($args -contains '-Stop' -and $alive) {{ Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue }}

if ($alive -and $sceneLoaded -and -not $luaErr) {{ Write-Host "SMOKE PASS"; exit 0 }}
Write-Host "SMOKE FAIL"; exit 1
'''


def sanitize_name(name):
    slug = re.sub(r"[^0-9a-zA-Z]+", "", name).lower()
    if not slug:
        raise SystemExit("error: --name must contain alphanumeric characters")
    return slug


def copy_gamekit(project_dir):
    dst = os.path.join(project_dir, "Assets", "Scripts", "gamekit")
    if os.path.exists(dst):
        shutil.rmtree(dst)
    shutil.copytree(mgk.GAMEKIT_SRC, dst)


def copy_prefabs(project_dir):
    dst = os.path.join(project_dir, "Assets", "Prefabs")
    os.makedirs(dst, exist_ok=True)
    for name in os.listdir(mgk.PREFABS_SRC):
        if name.endswith(".peprefab"):
            shutil.copyfile(os.path.join(mgk.PREFABS_SRC, name), os.path.join(dst, name))


def write_text(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def main():
    parser = argparse.ArgumentParser(description="Scaffold a PhasmaEngine mini-game")
    parser.add_argument("--name", required=True, help="project name (e.g. MyGame)")
    parser.add_argument("--template", default="topdown", choices=["topdown"],
                        help="scene template (slice 1: topdown only)")
    parser.add_argument("--dir", default=DEFAULT_DIR, help="parent directory for the project")
    parser.add_argument("--api", default="vulkan", choices=["vulkan", "dx12"],
                        help="graphics API the smoke runner launches with")
    parser.add_argument("--player-exe", default=DEFAULT_PLAYER_EXE,
                        help="path to PhasmaPlayer.exe for run_smoke.ps1")
    parser.add_argument("--update-gamekit", action="store_true",
                        help="only refresh the copied gamekit + prefab snapshot, then exit")
    args = parser.parse_args()

    name = args.name
    slug = sanitize_name(name)
    project_dir = os.path.join(args.dir, name)

    if args.update_gamekit:
        if not os.path.isdir(project_dir):
            raise SystemExit("error: project does not exist: " + project_dir)
        copy_gamekit(project_dir)
        copy_prefabs(project_dir)
        print("refreshed gamekit + prefabs in", project_dir)
        return

    if os.path.exists(os.path.join(project_dir, "phasma_project.json")):
        raise SystemExit("error: a project named '%s' already exists at %s" % (name, project_dir))

    os.makedirs(project_dir, exist_ok=True)

    # 1. project descriptor (exactly the 4 fields ProjectConfig parses)
    write_text(os.path.join(project_dir, "phasma_project.json"),
               json.dumps({
                   "version": 1,
                   "name": name,
                   "assets": "Assets",
                   "startup_scene": "Assets/Scenes/main.pescene",
               }, indent=4) + "\n")

    # 2. startup scene from the topdown template, wired to the entry script
    on_play = "Assets/Scripts/%s.lua" % slug
    scene = mgk.build_topdown_scene(on_play)
    write_text(os.path.join(project_dir, "Assets", "Scenes", "main.pescene"),
               json.dumps(scene, indent=4) + "\n")

    # 3. entry script
    write_text(os.path.join(project_dir, "Assets", "Scripts", "%s.lua" % slug),
               ENTRY_TEMPLATE.format(Name=name, name=slug))

    # 4. gamekit + 5. prefab pack (pinned snapshots)
    copy_gamekit(project_dir)
    copy_prefabs(project_dir)

    # 6. smoke runner
    write_text(os.path.join(project_dir, "run_smoke.ps1"),
               SMOKE_TEMPLATE.format(Name=name, exe=args.player_exe,
                                     project=project_dir, api=args.api))

    print("created project:", project_dir)
    print("  startup scene: Assets/Scenes/main.pescene")
    print("  entry script:  %s" % on_play)
    print("  smoke:         powershell -ExecutionPolicy Bypass -File \"%s\""
          % os.path.join(project_dir, "run_smoke.ps1"))


if __name__ == "__main__":
    main()
